/*Advanced util queries - Report usage */

var queries = {};

queries.TodayBestUsers="SELECT USER.USERID , USER.EMAIL , USER.FIRSTNAME , USER.LASTNAME , ORDERLIST.TOTALPRICE FROM ORDERLIST LEFT OUTER JOIN USER ON ORDERLIST.USERID=USER.USERID WHERE CURDATE()=ORDERLIST.OL_DTTM ORDER BY ORDERLIST.TOTALPRICE DESC";
queries.WeekBestUsers="SELECT USER.USERID , USER.EMAIL , USER.FIRSTNAME , USER.LASTNAME , ORDERLIST.TOTALPRICE FROM ORDERLIST LEFT OUTER JOIN USER ON ORDERLIST.USERID=USER.USERID WHERE WEEK(CURDATE())=WEEK(ORDERLIST.OL_DTTM) ORDER BY ORDERLIST.TOTALPRICE DESC";
queries.MonthBestUsers="SELECT USER.USERID , USER.EMAIL , USER.FIRSTNAME , USER.LASTNAME , ORDERLIST.TOTALPRICE FROM ORDERLIST LEFT OUTER JOIN USER ON ORDERLIST.USERID=USER.USERID WHERE MONTH(curdate())=MONTH(ORDERLIST.OL_DTTM) ORDER BY ORDERLIST.TOTALPRICE DESC";

queries.TodayBestItems="SELECT ITEM.ITEMID , ITEM.NAME , ORDEREDITEM.QTY , ITEM.PRICE FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDERLIST.OLID = ORDEREDITEM.OLID LEFT OUTER JOIN ITEM ON ITEM.ITEMID = ORDEREDITEM.ITEMID WHERE CURDATE() = CAST(ORDERLIST.OL_DTTM AS DATE) ORDER BY ORDEREDITEM.QTY DESC";
queries.WeekBestItems="SELECT ITEM.ITEMID , ITEM.NAME , ORDEREDITEM.QTY , ITEM.PRICE FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDERLIST.OLID = ORDEREDITEM.OLID LEFT OUTER JOIN ITEM ON ITEM.ITEMID = ORDEREDITEM.ITEMID WHERE WEEK(CURDATE()) = WEEK(CAST(ORDERLIST.OL_DTTM AS DATE)) ORDER BY ORDEREDITEM.QTY DESC";
queries.MonthBestItems="SELECT ITEM.ITEMID , ITEM.NAME , ORDEREDITEM.QTY , ITEM.PRICE FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDERLIST.OLID = ORDEREDITEM.OLID LEFT OUTER JOIN ITEM ON ITEM.ITEMID = ORDEREDITEM.ITEMID WHERE MONTH(CURDATE()) = MONTH(CAST(ORDERLIST.OL_DTTM AS DATE)) ORDER BY ORDEREDITEM.QTY DESC";

queries.TodayWorstItems="SELECT ITEM.ITEMID , ITEM.NAME , ORDEREDITEM.QTY , ITEM.PRICE FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDERLIST.OLID = ORDEREDITEM.OLID LEFT OUTER JOIN ITEM ON ITEM.ITEMID = ORDEREDITEM.ITEMID WHERE CURDATE() = CAST(ORDERLIST.OL_DTTM AS DATE) ORDER BY ORDEREDITEM.QTY ASC";
queries.WeekWorstItems="SELECT ITEM.ITEMID , ITEM.NAME , ORDEREDITEM.QTY , ITEM.PRICE FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDERLIST.OLID = ORDEREDITEM.OLID LEFT OUTER JOIN ITEM ON ITEM.ITEMID = ORDEREDITEM.ITEMID WHERE WEEK(CURDATE()) = WEEK(CAST(ORDERLIST.OL_DTTM AS DATE)) ORDER BY ORDEREDITEM.QTY ASC";
queries.MonthWorstItems="SELECT ITEM.ITEMID , ITEM.NAME , ORDEREDITEM.QTY , ITEM.PRICE FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDERLIST.OLID = ORDEREDITEM.OLID LEFT OUTER JOIN ITEM ON ITEM.ITEMID = ORDEREDITEM.ITEMID WHERE MONTH(CURDATE()) = MONTH(CAST(ORDERLIST.OL_DTTM AS DATE)) ORDER BY ORDEREDITEM.QTY ASC";

queries.TodayBestSuppliers="SELECT ITEM.NAME , SUM(ITEM.PRICE) , ITEM.SUPID FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDEREDITEM.OLID = ORDERLIST.OLID LEFT OUTER JOIN ITEM ON ITEM.ITEMID = ORDEREDITEM.ITEMID WHERE CURDATE() = CAST(ORDERLIST.OL_DTTM AS DATE) GROUP BY ITEM.SUPID ORDER BY TOTALPRICE DESC";
queries.WeekBestSuppliers="SELECT ITEM.NAME , SUM(ITEM.PRICE) , ITEM.SUPID FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDEREDITEM.OLID = ORDERLIST.OLID LEFT OUTER JOIN ITEM ON ITEM.ITEMID = ORDEREDITEM.ITEMID WHERE WEEK(CURDATE()) = WEEK(CAST(ORDERLIST.OL_DTTM AS DATE)) GROUP BY ITEM.SUPID ORDER BY TOTALPRICE DESC";
queries.MonthBestSuppliers="SELECT ITEM.NAME , SUM(ITEM.PRICE) , ITEM.SUPID FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDEREDITEM.OLID = ORDERLIST.OLID LEFT OUTER JOIN ITEM ON ITEM.ITEMID = ORDEREDITEM.ITEMID WHERE MONTH(CURDATE()) = MONTH(CAST(ORDERLIST.OL_DTTM AS DATE)) GROUP BY ITEM.SUPID ORDER BY TOTALPRICE DESC";

queries.WeekHardEmployee="SELECT EMPLOYEE.FIRSTNAME , EMPLOYEE.LASTNAME ,COUNT(*) FROM SHIFT LEFT OUTER JOIN EMPLOYEE ON EMPLOYEE.EMPID = SHIFT.EMPID WHERE WEEK(CAST(SHIFT.START_DTTM AS DATE)) = WEEK(CURDATE()) GROUP BY EMPLOYEE.EMPID ORDER BY COUNT(*) DESC";
queries.MonthHardEmployee="SELECT EMPLOYEE.FIRSTNAME , EMPLOYEE.LASTNAME ,COUNT(*) FROM SHIFT LEFT OUTER JOIN EMPLOYEE ON EMPLOYEE.EMPID = SHIFT.EMPID WHERE MONTH(CAST(SHIFT.START_DTTM AS DATE)) = MONTH(CURDATE()) GROUP BY EMPLOYEE.EMPID ORDER BY COUNT(*) DESC";


module.exports = queries;





