/*Advanced util queries - Report usage */

var queries = {};

queries.TodayBestUsers="SELECT USER.userid , USER.email , USER.firstname , USER.lastname , SUM(ORDERLIST.totalprice) total FROM ORDERLIST LEFT OUTER JOIN USER ON ORDERLIST.userid=USER.userid WHERE DAY(CURDATE())=DAY(ORDERLIST.OL_DTTM) GROUP BY USER.userid ORDER BY total DESC";
queries.WeekBestUsers="SELECT USER.userid , USER.email , USER.firstname , USER.lastname , SUM(ORDERLIST.totalprice) total FROM ORDERLIST LEFT OUTER JOIN USER ON ORDERLIST.userid=USER.userid WHERE WEEK(CURDATE())=WEEK(ORDERLIST.OL_DTTM) GROUP BY USER.userid ORDER BY total DESC";
queries.MonthBestUsers="SELECT USER.userid , USER.email , USER.firstname , USER.lastname , SUM(ORDERLIST.totalprice) total FROM ORDERLIST LEFT OUTER JOIN USER ON ORDERLIST.userid=USER.userid WHERE MONTH(curdate())=MONTH(ORDERLIST.OL_DTTM) GROUP BY USER.userid ORDER BY total DESC";

queries.TodayBestItems="SELECT ITEM.itemid , ITEM.name , ORDEREDITEM.qty , ITEM.price FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDERLIST.OLID = ORDEREDITEM.OLID LEFT OUTER JOIN ITEM ON ITEM.itemid = ORDEREDITEM.itemid WHERE DAY(CURDATE()) = DAY(ORDERLIST.OL_DTTM) ORDER BY ORDEREDITEM.qty DESC";
queries.WeekBestItems="SELECT ITEM.itemid , ITEM.name , ORDEREDITEM.qty , ITEM.price FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDERLIST.OLID = ORDEREDITEM.OLID LEFT OUTER JOIN ITEM ON ITEM.itemid = ORDEREDITEM.itemid WHERE WEEK(CURDATE()) = WEEK(ORDERLIST.OL_DTTM) ORDER BY ORDEREDITEM.qty DESC";
queries.MonthBestItems="SELECT ITEM.itemid , ITEM.name , ORDEREDITEM.qty , ITEM.price FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDERLIST.OLID = ORDEREDITEM.OLID LEFT OUTER JOIN ITEM ON ITEM.itemid = ORDEREDITEM.itemid WHERE MONTH(CURDATE()) = MONTH(ORDERLIST.OL_DTTM) ORDER BY ORDEREDITEM.qty DESC";

queries.TodayWorstItems="SELECT ITEM.itemid , ITEM.name , ORDEREDITEM.qty , ITEM.price FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDERLIST.OLID = ORDEREDITEM.OLID LEFT OUTER JOIN ITEM ON ITEM.itemid = ORDEREDITEM.itemid WHERE DAY(CURDATE()) = DAY(ORDERLIST.OL_DTTM) ORDER BY ORDEREDITEM.qty ASC";
queries.WeekWorstItems="SELECT ITEM.itemid , ITEM.name , ORDEREDITEM.qty , ITEM.price FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDERLIST.OLID = ORDEREDITEM.OLID LEFT OUTER JOIN ITEM ON ITEM.itemid = ORDEREDITEM.itemid WHERE WEEK(CURDATE()) = WEEK(ORDERLIST.OL_DTTM) ORDER BY ORDEREDITEM.qty ASC";
queries.MonthWorstItems="SELECT ITEM.itemid , ITEM.name , ORDEREDITEM.qty , ITEM.price FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDERLIST.OLID = ORDEREDITEM.OLID LEFT OUTER JOIN ITEM ON ITEM.itemid = ORDEREDITEM.itemid WHERE MONTH(CURDATE()) = MONTH(ORDERLIST.OL_DTTM) ORDER BY ORDEREDITEM.qty ASC";

queries.TodayBestSuppliers="SELECT ITEM.name , SUM(ITEM.price) total , ITEM.SUPID FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDEREDITEM.OLID = ORDERLIST.OLID LEFT OUTER JOIN ITEM ON ITEM.itemid = ORDEREDITEM.itemid WHERE DAY(CURDATE()) = DAY(ORDERLIST.OL_DTTM) GROUP BY ITEM.SUPID ORDER BY total DESC";
queries.WeekBestSuppliers="SELECT ITEM.name , SUM(ITEM.price) total , ITEM.SUPID FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDEREDITEM.OLID = ORDERLIST.OLID LEFT OUTER JOIN ITEM ON ITEM.itemid = ORDEREDITEM.itemid WHERE WEEK(CURDATE()) = WEEK(ORDERLIST.OL_DTTM) GROUP BY ITEM.SUPID ORDER BY total DESC";
queries.MonthBestSuppliers="SELECT ITEM.name , SUM(ITEM.price) total , ITEM.SUPID FROM ORDERLIST LEFT OUTER JOIN ORDEREDITEM ON ORDEREDITEM.OLID = ORDERLIST.OLID LEFT OUTER JOIN ITEM ON ITEM.itemid = ORDEREDITEM.itemid WHERE MONTH(CURDATE()) = MONTH(ORDERLIST.OL_DTTM) GROUP BY ITEM.SUPID ORDER BY total DESC";

queries.WeekHardEmployee="SELECT EMPLOYEE.firstname , EMPLOYEE.lastname ,COUNT(*) FROM SHIFT LEFT OUTER JOIN EMPLOYEE ON EMPLOYEE.EMPID = SHIFT.EMPID WHERE WEEK(SHIFT.START_DTTM) = WEEK(CURDATE()) GROUP BY EMPLOYEE.EMPID ORDER BY COUNT(*) DESC";
queries.MonthHardEmployee="SELECT EMPLOYEE.firstname , EMPLOYEE.lastname ,COUNT(*) FROM SHIFT LEFT OUTER JOIN EMPLOYEE ON EMPLOYEE.EMPID = SHIFT.EMPID WHERE MONTH(SHIFT.START_DTTM) = MONTH(CURDATE()) GROUP BY EMPLOYEE.EMPID ORDER BY COUNT(*) DESC";


module.exports = queries;





